version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: oneway-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    restart: unless-stopped
    environment:
      - DOMAIN=onewaycargo.com.br

networks:
  traefik:
    external: true 